### ISSUE TITLE
Live encoding input quality control

### ISSUE THREAD

**Issue by JeremieKlein** [bitmovin/flamefy-sync#2]
## Your Question
In the dashboard we can see you have a quality control information for live ingest feed (this is related to current FPS vs expected one)
Looking at your API I can't find where this information can be available.
I can find all other input monitoring information here https://bitmovin.com/docs/encoding/api-reference/sections/statistics#/Encoding/GetEncodingStatisticsEncodingsLiveStatisticsByEncodingId under statistics/streamInfos/streaminfosdetails

However nothing related to quality control. Do you have this information available? or do you have a method to calculate it based on information from the stream.

thanks

Jérémie

**Comment by luckygoyal-bitmovin** [comment]
@JeremieKlein , adding the information about calculation of Input health field in live encoding below. Closing the ticket. Please feel free to re-open if there are further questions.

Input health is calculated as below using below formula

```
  const streamInfo = videoStreamInfos[0];
  const targetFps = streamInfo.rate;
  const realFps = streamInfo.samplesReadPerSecondAvg;
  const percentageDifference = (1 - realFps / targetFps) * 100;
```

when percentageDifference < 5% --> GREEN
5% < percentageDifference  < 10% --> ORANGE
else --> RED
