### ISSUE TITLE
Some streams start buffering, load the m3u8 and first chunk and then it stalls

### ISSUE THREAD

**Issue by jamesdavidholding** [bitmovin/flamefy-sync#4]
## Player Details

**Platform/OS:**  Web
**Browser:** Chrome 
**Device:** 
**SDK Version:** Latest

## Reproduce
See steps below

**Stream URL:** 
https://videos.qwest.tv/content/f861fc46-0bfe-472d-ad06-884f7c447a5a

**Stream Type:**
- [ X] HLS 
- [ ] DASH
- [ ] Progressive

**DRM:**
- [ ] Yes: 
- [X ] No

**Steps to reproduce:** 
Navigate to:  https://videos.qwest.tv/content/f861fc46-0bfe-472d-ad06-884f7c447a5a

U: levi.miller@bitmovin.com 
P: 4rZ5UBvqVtnGT3U

Play stream and observe issue.

**Comment by jamesdavidholding** [comment]
Notes from engineering:

`#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="stereo",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,URI="https://bitmovin-a.akamaihd.net/content/sintel/hls/audio/stereo/en/128kbit.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="stereo",LANGUAGE="en",NAME="English",DEFAULT=NO,AUTOSELECT=YES,URI="https://bitmovin-a.akamaihd.net/content/sintel/hls/audio/stereo/none/128kbit.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=258157,AUDIO="stereo",RESOLUTION=422x180
https://bitmovin-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8`

**Notice the same name for both audio tracks. By changing one the asset plays correctly**

**Comment by jamesdavidholding** [comment]
I can see that the provided stream has now been amended so the audio track Name is now unique as is the URI.
1. = audio_160  both in name and bitrate
2. = audio_360 both in name and bitrate

Internal Engineering ticket id is: PW-4027 (we might be able to do an edge case handling on the Default setting)  however
If there are multiple audio tracks with the same language, name and no unique group for each we have no way to differentiate between them. If they contain different content, they need to be differentiated either by language or name or separated into different groups.

**Comment by luckygoyal-bitmovin** [comment]
@JeremieKlein , as per HLS specification (https://tools.ietf.org/html/draft-pantos-http-live-streaming-23), the NAME is expected to be unique.(snippet from specification below). This is something that should ideally be fixed on packaging side. Also it seems that this change is already done, so I would suggest to close this issue. Please feel free to share your questions/concerns.

> 4.3.4.1.1.  Rendition Groups
> 
>    A set of one or more EXT-X-MEDIA tags with the same GROUP-ID value
>    and the same TYPE value defines a Group of Renditions.  Each member
>    of the Group MUST be an alternative rendition of the same content;
>    otherwise playback errors can occur.
> 
>    All EXT-X-MEDIA tags in a Playlist MUST meet the following
>    constraints:
> 
>    o  All EXT-X-MEDIA tags in the same Group MUST have different NAME
>       attributes.

**Comment by jamesdavidholding** [comment]
Hi @JeremieKlein can this be closed? as per Lucky's comment, it seems the change on the stream has been made in line with the HLS specification?

**Comment by JeremieKlein** [comment]
Indeed can be closed. we managed to get the track name unique
